// React/pivot-table/src/App.js
import { PivotViewComponent, FieldList, Inject } from '@syncfusion/ej2-react-pivotview';
import * as React from 'react';
import './App.css';

function App() {
  let dataSourceSettings = {
    url: 'https://localhost:7161/Order',
    columns: [{ name: 'ShipName' }],
    values: [{ name: 'Freight', caption: 'Sum of Freight' },],
    rows: [{ name: 'ShipCity' }],
  };

  return (<PivotViewComponent id='PivotView' height={350} dataSourceSettings={dataSourceSettings} showFieldList={true}>
    <Inject services={[FieldList]}/></PivotViewComponent>);
};
export default App;

// Angular/pivot-table/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { IDataOptions, PivotView} from '@syncfusion/ej2-angular-pivotview';

@Component({
  selector: 'app-root',
  template: `<div class="col-md-8">
  <ejs-pivotview #pivotview id='PivotView' height='350' [dataSourceSettings]=dataSourceSettings showFieldList='true'></ejs-pivotview></div>
  `
})

export class AppComponent {
    public dataSourceSettings: IDataOptions;
    @ViewChild('pivotview', {static: false})
    public pivotGridObj: PivotView;
    ngOnInit(): void {
        this.dataSourceSettings = {
          url: 'https://localhost:7146/Pivot',
          columns: [{ name: 'ShipName' }],
          values: [{ name: 'Freight', caption: 'Sum of Freight' },],
          rows: [{ name: 'ShipCity' }],
        }     
    }
}
